version: '3.8'
services:
  postgres:
    image: postgres # Utiliza la última versión que existe en docker
    restart: always #En caso de fallo reinicia el servidor
    ports:
      - "5432:5432" #Para indicarle en que puerto ejecutarse
    environment: #Configuraciones iniciales
      DATABASE_HOST : 127.0.0.1
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: julian
      POSTGRES_BD : bdpadeltussam
     
    volumes:
      - postgres:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 80:80 #Primero el puerto local
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  ktor:
    build: ./back-tussam
    ports:
      - 8080:8080
    depends_on:
      - postgres


volumes:
  postgres:
  pgadmin:
